/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Front_end.Formularios;
import Controladores.CRUDClientes;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
/**
 *
 * @author Andres
 */
public class FormClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormClientes
     */
    public FormClientes() {
        initComponents();
        
        CRUDClientes objCliente = new CRUDClientes();
        objCliente.mostrarClientes(tbClientes);
        
        tbClientes.setRowHeight(40);
        
        //Darle estilo al jtable
        
        JTableHeader header = tbClientes.getTableHeader();
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable tbClientes, Object value, boolean isSelected,
                                                           boolean hasFocus, int row, int column) {
                JLabel label = new JLabel(value.toString());
                label.setOpaque(true);
                label.setBackground(new Color(37, 39, 64)); // Color de fondo
                label.setForeground(Color.WHITE); // Color del texto
                label.setFont(new Font("Roboto", Font.BOLD, 14)); // Estilo de texto
                label.setHorizontalAlignment(SwingConstants.CENTER); // Alineación
                label.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
                return label;
            }
        });
        
        //Hacer que al momento de dar enter en el ultimo campo se agregre un cliente
        
        txtTelefono1.addKeyListener(new java.awt.event.KeyAdapter(){
        @Override
        public void keyPressed(java.awt.event.KeyEvent evt){
            if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                try {
                    objCliente.AgregarClientes(txtNombreCompa, txtNombre, txtTitulo, txtDireccion, txtCiudad, txtCP, txtPais, txtTelefono1);
                    objCliente.mostrarClientes(tbClientes);
                    objCliente.limpiarCampos(txtIdCliente, txtNombreCompa, txtNombre, txtTitulo, txtDireccion, txtCiudad, txtCP, txtPais, txtTelefono1);
        } catch (SQLException ex) {
            Logger.getLogger(FormProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        }
        
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCP = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtNombreCompa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JPanel();
        btnGuardarCliente = new javax.swing.JLabel();
        btnModificar = new javax.swing.JPanel();
        btnEditarCliente = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        btnEliminarCliente = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        btnLimpiarCampos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        bg1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        txtIdCliente1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCP1 = new javax.swing.JTextField();
        txtDireccion1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPais1 = new javax.swing.JTextField();
        txtCiudad1 = new javax.swing.JTextField();
        txtTitulo1 = new javax.swing.JTextField();
        txtNombreCompa1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTelefono2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnGuardarProductos1 = new javax.swing.JPanel();
        btnGuardarCliente1 = new javax.swing.JLabel();
        btnModificar2 = new javax.swing.JPanel();
        btnEditarCliente1 = new javax.swing.JLabel();
        btnEliminar2 = new javax.swing.JPanel();
        btnEliminarCliente1 = new javax.swing.JLabel();
        btnLimpiar2 = new javax.swing.JPanel();
        btnLimpiarCampos1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProductos1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Clientes");

        bg.setBackground(new java.awt.Color(39, 38, 67));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(34, 32, 52));

        jLabel12.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(124, 113, 221));
        jLabel12.setText("Registrar nuevo cliente");

        jLabel112.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(249, 249, 249));
        jLabel112.setText("Id Cliente:");

        txtIdCliente.setEditable(false);
        txtIdCliente.setBackground(new java.awt.Color(34, 32, 52));
        txtIdCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtIdCliente.setForeground(new java.awt.Color(229, 229, 229));
        txtIdCliente.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 249, 249));
        jLabel2.setText("Nombre contacto:");

        txtNombre.setBackground(new java.awt.Color(34, 32, 52));
        txtNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(229, 229, 229));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 249, 249));
        jLabel6.setText("Dirección:");

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 249, 249));
        jLabel8.setText("Codigo postal:");

        txtCP.setBackground(new java.awt.Color(34, 32, 52));
        txtCP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCP.setForeground(new java.awt.Color(229, 229, 229));

        txtDireccion.setBackground(new java.awt.Color(34, 32, 52));
        txtDireccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(229, 229, 229));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 249, 249));
        jLabel1.setText("Nombre compañia:");

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 249, 249));
        jLabel3.setText("Titulo contacto:");

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 249, 249));
        jLabel7.setText("Ciudad:");

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 249, 249));
        jLabel9.setText("Telefono:");

        txtPais.setBackground(new java.awt.Color(34, 32, 52));
        txtPais.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPais.setForeground(new java.awt.Color(229, 229, 229));

        txtCiudad.setBackground(new java.awt.Color(34, 32, 52));
        txtCiudad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(229, 229, 229));

        txtTitulo.setBackground(new java.awt.Color(34, 32, 52));
        txtTitulo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(229, 229, 229));

        txtNombreCompa.setBackground(new java.awt.Color(34, 32, 52));
        txtNombreCompa.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombreCompa.setForeground(new java.awt.Color(229, 229, 229));

        jLabel10.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(249, 249, 249));
        jLabel10.setText("Pais:");

        txtTelefono1.setBackground(new java.awt.Color(34, 32, 52));
        txtTelefono1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTelefono1.setForeground(new java.awt.Color(229, 229, 229));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel112)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreCompa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtTitulo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtCiudad))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtPais)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel112)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCompa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 700, 290));

        jPanel2.setBackground(new java.awt.Color(34, 32, 52));

        btnGuardar.setBackground(new java.awt.Color(33, 169, 66));

        btnGuardarCliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnGuardarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardarCliente.setText("GUARDAR");
        btnGuardarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarClienteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnModificar.setBackground(new java.awt.Color(35, 108, 176));

        btnEditarCliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btnEditarCliente.setText("EDITAR");
        btnEditarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarClienteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnModificarLayout = new javax.swing.GroupLayout(btnModificar);
        btnModificar.setLayout(btnModificarLayout);
        btnModificarLayout.setHorizontalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnModificarLayout.setVerticalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnEliminar.setBackground(new java.awt.Color(224, 51, 68));

        btnEliminarCliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnEliminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminarCliente.setText("ELIMINAR");
        btnEliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarClienteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnLimpiar.setBackground(new java.awt.Color(28, 160, 184));

        btnLimpiarCampos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnLimpiarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarCampos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLimpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/escoba.png"))); // NOI18N
        btnLimpiarCampos.setText("LIMPIAR");
        btnLimpiarCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarCamposMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarCamposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarCamposMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 270, 290));

        tbClientes.setBackground(new java.awt.Color(80, 77, 130));
        tbClientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tbClientes.setForeground(new java.awt.Color(255, 255, 255));
        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClientes);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 970, 240));

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setTitle("Clientes");

        bg1.setBackground(new java.awt.Color(39, 38, 67));
        bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(34, 32, 52));

        jLabel13.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(124, 113, 221));
        jLabel13.setText("Registrar nuevo cliente");

        jLabel113.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(249, 249, 249));
        jLabel113.setText("Id Cliente:");

        txtIdCliente1.setEditable(false);
        txtIdCliente1.setBackground(new java.awt.Color(34, 32, 52));
        txtIdCliente1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtIdCliente1.setForeground(new java.awt.Color(229, 229, 229));
        txtIdCliente1.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(249, 249, 249));
        jLabel4.setText("Nombre contacto:");

        txtNombre1.setBackground(new java.awt.Color(34, 32, 52));
        txtNombre1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombre1.setForeground(new java.awt.Color(229, 229, 229));

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(249, 249, 249));
        jLabel11.setText("Dirección:");

        jLabel14.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(249, 249, 249));
        jLabel14.setText("Codigo postal:");

        txtCP1.setBackground(new java.awt.Color(34, 32, 52));
        txtCP1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCP1.setForeground(new java.awt.Color(229, 229, 229));

        txtDireccion1.setBackground(new java.awt.Color(34, 32, 52));
        txtDireccion1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDireccion1.setForeground(new java.awt.Color(229, 229, 229));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(249, 249, 249));
        jLabel5.setText("Nombre compañia:");

        jLabel15.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(249, 249, 249));
        jLabel15.setText("Titulo contacto:");

        jLabel16.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(249, 249, 249));
        jLabel16.setText("Ciudad:");

        jLabel17.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(249, 249, 249));
        jLabel17.setText("Telefono:");

        txtPais1.setBackground(new java.awt.Color(34, 32, 52));
        txtPais1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPais1.setForeground(new java.awt.Color(229, 229, 229));

        txtCiudad1.setBackground(new java.awt.Color(34, 32, 52));
        txtCiudad1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCiudad1.setForeground(new java.awt.Color(229, 229, 229));

        txtTitulo1.setBackground(new java.awt.Color(34, 32, 52));
        txtTitulo1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTitulo1.setForeground(new java.awt.Color(229, 229, 229));

        txtNombreCompa1.setBackground(new java.awt.Color(34, 32, 52));
        txtNombreCompa1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombreCompa1.setForeground(new java.awt.Color(229, 229, 229));

        jLabel18.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(249, 249, 249));
        jLabel18.setText("Pais:");

        txtTelefono2.setBackground(new java.awt.Color(34, 32, 52));
        txtTelefono2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTelefono2.setForeground(new java.awt.Color(229, 229, 229));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel113)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtCP1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreCompa1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtTitulo1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(txtCiudad1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(txtPais1)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel113)
                    .addComponent(jLabel5)
                    .addComponent(txtNombreCompa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel15)
                    .addComponent(txtTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16)
                    .addComponent(txtCiudad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(txtPais1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        bg1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 700, 290));

        jPanel4.setBackground(new java.awt.Color(34, 32, 52));

        btnGuardarProductos1.setBackground(new java.awt.Color(33, 169, 66));

        btnGuardarCliente1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnGuardarCliente1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardarCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardarCliente1.setText("GUARDAR");
        btnGuardarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarCliente1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardarCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarCliente1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarCliente1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarCliente1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarProductos1Layout = new javax.swing.GroupLayout(btnGuardarProductos1);
        btnGuardarProductos1.setLayout(btnGuardarProductos1Layout);
        btnGuardarProductos1Layout.setHorizontalGroup(
            btnGuardarProductos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardarCliente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btnGuardarProductos1Layout.setVerticalGroup(
            btnGuardarProductos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardarCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnModificar2.setBackground(new java.awt.Color(35, 108, 176));

        btnEditarCliente1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnEditarCliente1.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditarCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btnEditarCliente1.setText("EDITAR");
        btnEditarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarCliente1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarCliente1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarCliente1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnModificar2Layout = new javax.swing.GroupLayout(btnModificar2);
        btnModificar2.setLayout(btnModificar2Layout);
        btnModificar2Layout.setHorizontalGroup(
            btnModificar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditarCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnModificar2Layout.setVerticalGroup(
            btnModificar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditarCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnEliminar2.setBackground(new java.awt.Color(224, 51, 68));

        btnEliminarCliente1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnEliminarCliente1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminarCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminarCliente1.setText("ELIMINAR");
        btnEliminarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarCliente1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarCliente1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarCliente1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEliminar2Layout = new javax.swing.GroupLayout(btnEliminar2);
        btnEliminar2.setLayout(btnEliminar2Layout);
        btnEliminar2Layout.setHorizontalGroup(
            btnEliminar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnEliminar2Layout.setVerticalGroup(
            btnEliminar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnLimpiar2.setBackground(new java.awt.Color(28, 160, 184));

        btnLimpiarCampos1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnLimpiarCampos1.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarCampos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLimpiarCampos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/escoba.png"))); // NOI18N
        btnLimpiarCampos1.setText("LIMPIAR");
        btnLimpiarCampos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarCampos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarCampos1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarCampos1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarCampos1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLimpiar2Layout = new javax.swing.GroupLayout(btnLimpiar2);
        btnLimpiar2.setLayout(btnLimpiar2Layout);
        btnLimpiar2Layout.setHorizontalGroup(
            btnLimpiar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiarCampos1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btnLimpiar2Layout.setVerticalGroup(
            btnLimpiar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiarCampos1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardarProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnModificar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(btnGuardarProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        bg1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 270, 290));

        tbProductos1.setBackground(new java.awt.Color(80, 77, 130));
        tbProductos1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tbProductos1.setForeground(new java.awt.Color(255, 255, 255));
        tbProductos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbProductos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProductos1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbProductos1);

        bg1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 970, 240));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 513, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 514, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 277, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 277, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarClienteMouseClicked
        CRUDClientes clientes = new CRUDClientes();
        try {
            
            clientes.AgregarClientes(txtNombreCompa, txtNombre, txtTitulo, txtDireccion, txtCiudad, txtCP, txtPais, txtTelefono1);
            clientes.mostrarClientes(tbClientes);
            clientes.limpiarCampos(txtIdCliente, txtNombreCompa, txtNombre, txtTitulo, txtDireccion, txtCiudad, txtCP, txtPais, txtTelefono1);
        
        } catch (SQLException ex) {
            Logger.getLogger(FormProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarClienteMouseClicked

    private void btnGuardarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarClienteMouseEntered
        btnGuardar.setBackground(new Color(45, 117, 80));
    }//GEN-LAST:event_btnGuardarClienteMouseEntered

    private void btnGuardarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarClienteMouseExited
        btnGuardar.setBackground(new Color(33, 169, 66));
    }//GEN-LAST:event_btnGuardarClienteMouseExited

    private void btnEditarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarClienteMouseClicked
        CRUDClientes clientes = new CRUDClientes();
        try {
            clientes.modificarClientes(txtIdCliente, txtNombreCompa, txtNombre, txtTitulo, txtDireccion, txtCiudad, txtCP, txtPais, txtTelefono1);
            clientes.mostrarClientes(tbClientes);
            clientes.limpiarCampos(txtIdCliente, txtNombreCompa, txtNombre, txtTitulo, txtDireccion, txtCiudad, txtCP, txtPais, txtTelefono1);
        } catch (SQLException ex) {
            Logger.getLogger(FormClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditarClienteMouseClicked

    private void btnEditarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarClienteMouseEntered
        btnModificar.setBackground(new Color(23, 72, 117));
    }//GEN-LAST:event_btnEditarClienteMouseEntered

    private void btnEditarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarClienteMouseExited
        btnModificar.setBackground(new Color(35, 108, 176));
    }//GEN-LAST:event_btnEditarClienteMouseExited

    private void btnEliminarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarClienteMouseClicked
        CRUDClientes clientes = new CRUDClientes();
        try {
            
            int opcion = JOptionPane.showConfirmDialog
            (
            null, 
            "¿Estás seguro de que deseas eliminar este cliente?", 
            "Confirmar Eliminación", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
            );
            
            // Verifica la respuesta del usuario
            if (opcion == JOptionPane.YES_OPTION) 
            {
                clientes.borrarCliente(txtIdCliente);
                clientes.mostrarClientes(tbClientes);
                clientes.limpiarCampos(txtIdCliente, txtNombreCompa, txtNombre, txtTitulo, txtDireccion, txtCiudad, txtCP, txtPais, txtTelefono1);
                
            } else 
            {
                JOptionPane.showMessageDialog(null, "Operacion cancelada");
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(FormClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarClienteMouseClicked

    private void btnEliminarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarClienteMouseEntered
        btnEliminar.setBackground(new Color(149, 34, 45));
    }//GEN-LAST:event_btnEliminarClienteMouseEntered

    private void btnEliminarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarClienteMouseExited
        btnEliminar.setBackground(new Color(224, 51, 68));
    }//GEN-LAST:event_btnEliminarClienteMouseExited

    private void btnLimpiarCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarCamposMouseClicked
        CRUDClientes clientes = new CRUDClientes();
        clientes.limpiarCampos(txtIdCliente, txtNombreCompa, txtNombre, txtTitulo, txtDireccion, txtCiudad, txtCP, txtPais, txtTelefono1);
    }//GEN-LAST:event_btnLimpiarCamposMouseClicked

    private void btnLimpiarCamposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarCamposMouseEntered
        btnLimpiar.setBackground(new Color(18, 106, 122));
    }//GEN-LAST:event_btnLimpiarCamposMouseEntered

    private void btnLimpiarCamposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarCamposMouseExited
        btnLimpiar.setBackground(new Color(28, 160, 184));
    }//GEN-LAST:event_btnLimpiarCamposMouseExited

    private void tbClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientesMouseClicked
        CRUDClientes clientes = new CRUDClientes();
        clientes.Seleccionar(tbClientes, txtIdCliente, txtNombreCompa, txtNombre, txtTitulo, txtDireccion, txtCiudad, txtCP, txtPais, txtTelefono1);
    }//GEN-LAST:event_tbClientesMouseClicked

    private void btnGuardarCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCliente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCliente1MouseClicked

    private void btnGuardarCliente1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCliente1MouseEntered
        
    }//GEN-LAST:event_btnGuardarCliente1MouseEntered

    private void btnGuardarCliente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCliente1MouseExited
        
    }//GEN-LAST:event_btnGuardarCliente1MouseExited

    private void btnEditarCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCliente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarCliente1MouseClicked

    private void btnEditarCliente1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCliente1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarCliente1MouseEntered

    private void btnEditarCliente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCliente1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarCliente1MouseExited

    private void btnEliminarCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCliente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCliente1MouseClicked

    private void btnEliminarCliente1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCliente1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCliente1MouseEntered

    private void btnEliminarCliente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCliente1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCliente1MouseExited

    private void btnLimpiarCampos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarCampos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarCampos1MouseClicked

    private void btnLimpiarCampos1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarCampos1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarCampos1MouseEntered

    private void btnLimpiarCampos1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarCampos1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarCampos1MouseExited

    private void tbProductos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProductos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbProductos1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg1;
    private javax.swing.JLabel btnEditarCliente;
    private javax.swing.JLabel btnEditarCliente1;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnEliminar2;
    private javax.swing.JLabel btnEliminarCliente;
    private javax.swing.JLabel btnEliminarCliente1;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JLabel btnGuardarCliente;
    private javax.swing.JLabel btnGuardarCliente1;
    private javax.swing.JPanel btnGuardarProductos1;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JPanel btnLimpiar2;
    private javax.swing.JLabel btnLimpiarCampos;
    private javax.swing.JLabel btnLimpiarCampos1;
    private javax.swing.JPanel btnModificar;
    private javax.swing.JPanel btnModificar2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTable tbProductos1;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtCP1;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCiudad1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdCliente1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombreCompa;
    private javax.swing.JTextField txtNombreCompa1;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPais1;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtTelefono2;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTitulo1;
    // End of variables declaration//GEN-END:variables
}
