/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Front_end.Formularios;

import Controladores.DaoReporte;
import Models.PanelConFondo;
import Models.Reporte;
import com.toedter.calendar.JDateChooser;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author GORDILLO
 */
public class GenerarReporteView extends javax.swing.JPanel {
    
   
    
    /**
     * Creates new form Reporte
     * @param act
     */
    public GenerarReporteView() {
        
        initComponents();
       
        //Este es el frame del fondo
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(700, 332);
        
        int frameW = frame.getWidth();
        int frameH = frame.getHeight();
     
        //Y este es el panel a donde se le agregan todos los componentes 
        PanelConFondo fondo = new PanelConFondo("src\\imagenes\\GenerarReporte.png");
       
        
        //Declaramos los componentes y los agregamos
        JDateChooser inicioReporte = new JDateChooser();
        inicioReporte.setBounds(410,128,180,25);
        
        JDateChooser finReporte = new JDateChooser();
        finReporte.setBounds(410,180,180,25);
        
        ImageIcon icono = new ImageIcon("src/imagenes/generar.png");
        JButton generar = new JButton(icono);
        
        generar.addMouseListener(new MouseListener() {
            
            @Override public void mouseClicked(MouseEvent e) {
                try{                    
                
                Date primero = inicioReporte.getDate();
       
                Date segundo = finReporte.getDate();
                ReporteView act = new ReporteView(new Reporte(DaoReporte.getVentas(primero, segundo)));
                act.setVisible(true);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Ingresa una fecha valida");
                }
                
            } 

            @Override
            public void mouseEntered(MouseEvent e) {
                 generar.setIcon(new ImageIcon("src/imagenes/generar2.png"));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                 generar.setIcon(new ImageIcon("src/imagenes/generar.png"));
            }
            
            //No fueron implementados
            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }
        });
        
        generar.setBounds(210,240,100,25);
        
        ImageIcon icono2 = new ImageIcon("src/imagenes/cerrar.png");
        JButton cerrar = new JButton(icono2);
        
        cerrar.addMouseListener(new MouseListener() { 
            @Override public void mouseClicked(MouseEvent e) {
                frame.dispose();
            } 

            @Override
            public void mouseEntered(MouseEvent e) {
                 cerrar.setIcon(new ImageIcon("src/imagenes/cerrar2.png"));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                 cerrar.setIcon(new ImageIcon("src/imagenes/cerrar.png"));
            }
            
            //No fueron implementados
            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }
        });
        
        cerrar.setBounds(340,240,100,25);
        
        //Agregamos todos los componentes al panel
        
        fondo.add(inicioReporte);
        fondo.add(finReporte);
        fondo.add(generar);
        fondo.add(cerrar);
        frame.add(fondo);
        
        frame.setVisible(true);
    }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(700, 332));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
